version: "3.8"

volumes:
  home:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atis
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      PACKWIZ_REPO_PATH: /home/appuser/unnamed-modpack
      DB_PATH: /db
      RUST_LOG: warn,atis=debug
    volumes:
      - ./sled_db:/db
      - home:/home/appuser
